name: test

on:
  issues:
    types: [labeled]
  pull_request_target:
    types: [labeled]

permissions:
  issues: write
  pull-requests: write

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Payload
        run: |
          echo "name: ${{ github.event_name }}"
          echo "issue num: ${{ github.event.issue.number }}"
          echo "PR num: ${{ github.event.pull_request.number }}"
          cat $GITHUB_EVENT_PATH
      
  i-comment:
    if: ${{ (github.event.label.name == 'my label' && github.event_name == 'issues') }}
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            My issue comment
  p-comment:
    if: ${{ github.event.label.name == 'my label' }}
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            My pr comment
